# Generated by Django 3.1.1 on 2020-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
